import * as dotenv from 'dotenv';
import { database } from '../database';

// Load environment variables
dotenv.config({ path: '.env.local' });

async function cleanupAutoGeneratedQuestions() {
  console.log('🧹 Cleaning Up Auto-Generated Question Sets\n');
  console.log('='.repeat(60));

  try {
    // Test connection
    const connected = await database.testConnection();
    if (!connected) {
      throw new Error('Database connection failed');
    }

    const client = await database.getClient();

    try {
      // Get all question sets
      const allSets = await client.query(`
        SELECT id, user_uid, entry_date, created_at
        FROM journal_questions
        ORDER BY created_at DESC;
      `);

      console.log(`\n📊 Current question sets in database: ${allSets.rows.length}\n`);

      allSets.rows.forEach((row, index) => {
        const isDefault = row.user_uid === 'default_template';
        const label = isDefault ? '📋 [DEFAULT TEMPLATE]' : '👤 [USER SET]';
        console.log(`${index + 1}. ${label} ${row.user_uid} @ ${row.entry_date.toISOString().split('T')[0]} (created: ${row.created_at.toISOString().split('T')[0]})`);
      });

      console.log('\n' + '-'.repeat(60));
      console.log('\n💡 Recommendation:');
      console.log('   - Keep: default_template (required for default questions)');
      console.log('   - Delete: All user-specific question sets (auto-generated)');
      console.log('   - Users will get default template on-the-fly without database writes\n');

      // Count user sets (excluding default_template)
      const userSets = await client.query(`
        SELECT COUNT(*) as count
        FROM journal_questions
        WHERE user_uid != 'default_template';
      `);

      const userSetCount = parseInt(userSets.rows[0].count);

      if (userSetCount > 0) {
        console.log(`⚠️  Found ${userSetCount} auto-generated question set(s) to clean up\n`);
        console.log('🗑️  Deleting auto-generated question sets...\n');

        // Delete all user-specific question sets
        const deleteResult = await client.query(`
          DELETE FROM journal_questions
          WHERE user_uid != 'default_template'
          RETURNING user_uid, entry_date;
        `);

        deleteResult.rows.forEach((row, index) => {
          console.log(`   ${index + 1}. Deleted: ${row.user_uid} @ ${row.entry_date.toISOString().split('T')[0]}`);
        });

        console.log(`\n✅ Deleted ${deleteResult.rows.length} auto-generated question set(s)`);
      } else {
        console.log('✅ No auto-generated question sets found. Database is clean!');
      }

      // Show final state
      console.log('\n' + '='.repeat(60));
      console.log('\n📊 Final State:\n');

      const finalSets = await client.query(`
        SELECT user_uid, entry_date
        FROM journal_questions
        ORDER BY created_at DESC;
      `);

      finalSets.rows.forEach((row, index) => {
        const isDefault = row.user_uid === 'default_template';
        const label = isDefault ? '📋 [DEFAULT TEMPLATE]' : '👤 [USER SET]';
        console.log(`   ${index + 1}. ${label} ${row.user_uid} @ ${row.entry_date.toISOString().split('T')[0]}`);
      });

      console.log(`\n   Total: ${finalSets.rows.length} question set(s) (should be 1: default_template)\n`);

      console.log('='.repeat(60));
      console.log('\n✅ Cleanup completed successfully!\n');

      console.log('💡 Moving forward:');
      console.log('   - GET /api/journal-questions → Returns default template (no DB write)');
      console.log('   - POST /api/journal → Saves user answers to journal_entries');
      console.log('   - Questions are read-only, answers are in separate table\n');

    } finally {
      client.release();
    }

    await database.close();
    process.exit(0);
  } catch (error) {
    console.error('\n❌ Cleanup failed:', error);
    await database.close();
    process.exit(1);
  }
}

cleanupAutoGeneratedQuestions();

