-- Create solutions table to store both-crews API responses
-- This table stores solutions generated for each journal entry

CREATE TABLE IF NOT EXISTS solutions (
    id SERIAL PRIMARY KEY,
    user_uid VARCHAR(255) NOT NULL,
    entry_date DATE NOT NULL,
    journal_entry_id INTEGER NOT NULL,
    solution JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Foreign key constraints
    CONSTRAINT fk_solution_user_uid FOREIGN KEY (user_uid) REFERENCES users(uid) ON DELETE CASCADE,
    CONSTRAINT fk_solution_journal_entry FOREIGN KEY (journal_entry_id) REFERENCES journal_entries(id) ON DELETE CASCADE
);

-- Create index on user_uid for fast user lookups
CREATE INDEX IF NOT EXISTS idx_solutions_user_uid ON solutions(user_uid);

-- Create index on entry_date for date-based queries
CREATE INDEX IF NOT EXISTS idx_solutions_entry_date ON solutions(entry_date);

-- Create index on journal_entry_id for lookup by journal entry
CREATE INDEX IF NOT EXISTS idx_solutions_journal_entry_id ON solutions(journal_entry_id);

-- Create composite index for user + date lookups
CREATE INDEX IF NOT EXISTS idx_solutions_user_date ON solutions(user_uid, entry_date DESC);

-- Add comment to explain the table
COMMENT ON TABLE solutions IS 
'Stores solutions generated by the both-crews API for journal entries';



